#include "common.h"

int loadchandb(char *filename) {
    FILE *fp;
    channel *cp; /* Current channel will be here */
    char line[1024]; /* Large buffer, just incase */
    char *charp;
    int loaded = 0;

    if (!(fp = fopen(filename, "r"))) {
        printlog("Could not open channel file %s.", filename);
        return 0;
    }

    while((fgets(line, 1023, fp))) {
        /* Read out the line and skip any comments and empty lines too. */
        /* Valid comments are: # and // */
        if (line[0] == '#' || (line[0] == '/' && line[1] == '/') || line[0] == '\n' || line[0] == '\r')
            continue;

        /* Remove the end-of-line chars here */
        for (charp = line; *charp; charp++) {
            if (*charp == '\n' || *charp == '\r') {
                *charp = '\0';
                break;
            }
        }

        /* Is the line long enough? */
        /* It needs to be atleast 3 chars long */
        /* [#channel] or key=setting */
        if (strlen(line) < 3)
            continue;

        /* Find channelname or setting */
        if (line[0] == '[') {
            for (charp = &(line[1]); *charp; charp++) {
                if (*charp == ']') {
                    *charp = '\0';
                    break;
                }
            }
            if (!(cp = findchannel(&(line[1]))))
                cp = addchannel(&(line[1]));
            loaded++;
            continue;
        }

        /* Next line must be a setting */
        if (cp) {
            for (charp = line; *charp; charp++) {
                if (*charp == '=') {
                    *charp = '\0';

                    /* Make sure the setting isn't empty */
                    if (!strlen(charp + 1))
                      break;

                    /* Now check the input and assign accordingly */
                    if (!strcasecmp(line, "createdat")) {
                        cp->createdat = (time_t)atoll(charp + 1);
                    } else if (!strcasecmp(line, "lastjoin")) {
                        cp->lastjoin = (time_t)atoll(charp + 1);
                    } else if (!strcasecmp(line, "flags")) {
                        cp->flags = atoi(charp + 1);
                    }
                }
            }
        }
    }

    fclose(fp);

    return loaded;
}

int savechandb(char *filename) {
    FILE *fp;
    channel *cp;
    int saved = 0;
    
    if (!(fp = fopen(filename, "w"))) {
        printlog("chandb: Could not open channel file %s for saving.", filename);
        return 0;
    }
    
    fprintf(fp, "// Please do not modify this file on your own\n"
                "// It is generated by the bot and modifying may result in bad behaviour\n");

    for (cp = channels; cp; cp = cp->next) {
        fprintf(fp, "[%s]\n", cp->name);
        fprintf(fp, "createdat=%lu\n", cp->createdat);
        fprintf(fp, "lastjoin=%lu\n", cp->lastjoin);
        fprintf(fp, "flags=%d\n\n", cp->flags);
        saved++;
    }

    fclose(fp);

    return saved;
}

int loaduserdb(char *filename) {
    FILE *fp;
    dbuser *dup;
    account *ap;
    channel *cp = NULL;
    chanlevel *clp = NULL;
    char line[1024]; /* Large buffer, just incase */
    char *charp;
    int loaded = 0;

    if (!(fp = fopen(filename, "r"))) {
        printlog("Could not open user file %s.", filename);
        return 0;
    }

    while((fgets(line, 1023, fp))) {
        /* Read out the line and skip any comments and empty lines too. */
        /* Valid comments are: # and // */
        if (line[0] == '#' || (line[0] == '/' && line[1] == '/') || line[0] == '\n' || line[0] == '\r')
            continue;

        /* Remove the end-of-line chars here */
        for (charp = line; *charp; charp++) {
            if (*charp == '\n' || *charp == '\r') {
                *charp = '\0';
                break;
            }
        }

        /* Is the line long enough? */
        /* It needs to be atleast 3 chars long */
        /* [#account] or <#channel> or key=setting */
        if (strlen(line) < 3)
            continue;

        /* Find accountname or setting */
        if (line[0] == '[') {
            for (charp = &(line[1]); *charp; charp++) {
                if (*charp == ']') {
                    *charp = '\0';
                    break;
                }
            }
            if (!(ap = findaccount(&(line[1]))))
                ap = addaccount(&(line[1]));
            
            printlog("added new account: %s", ap->name);

            dup = newdbuser();
            /* Link account with dbuser */
            ap->dbuser = dup;
            dup->account = ap;
            cp = NULL;
            clp = NULL;
            loaded++;
            continue;
        }

        /* Next line must be a setting */
        if (ap) {
            if (line[0] == '<') {
                for (charp = &(line[1]); *charp; charp++) {
                    if (*charp == '>') {
                        *charp = '\0';
                        break;
                    }
                }
                cp = findchannel(&(line[1]));
                if (cp)
                    clp = addchanlevel(cp, ap);
                continue;
             }
             
             for (charp = line; *charp; charp++) {
                 if (*charp == '=') {
                     *charp = '\0';

                     /* Make sure the setting isn't empty */
                     if (!strlen(charp + 1))
                         break;

                     /* Now check the input and assign accordingly */
                     if (cp && clp) {
                         /* This is a chanlevel entry */
                         if (!strcasecmp(line, "lastchanged")) {
                             clp->lastchanged = (time_t)atoll(charp + 1);
                         } else if (!strcasecmp(line, "lastseen")) {
                             clp->lastseen = (time_t)atoll(charp + 1);
                         } else if (!strcasecmp(line, "flags")) {
                             clp->flags = atoi(charp + 1);
                         }
                     } else {
                         /* This is a dbuser entry */
                         if (!strcasecmp(line, "flags")) {
                            ap->dbuser->flags = atoi(charp + 1);
                         } else if (!strcasecmp(line, "lastseen")) {
                             ap->dbuser->lastseen = (time_t)atoll(charp + 1);
                         } else if (!strcasecmp(line, "trigger")) {
                             ap->dbuser->trigger = atoi(charp + 1);
                         }
                     }
                }
            }
        }
    }

    fclose(fp);
    return loaded;
}

int saveuserdb(char *filename) {
    FILE *fp;
    chanlevel *clp;
    bucket *bp;
    account *ap;
    int saved = 0, i;

    if (!(fp = fopen(filename, "w"))) {
        printlog("userdb: Could not open user file %s for saving.", filename);
        return 0;
    }
    
    fprintf(fp, "// Please do not modify this file on your own\n"
                "// It is generated by the bot and modifying may result in bad behaviour\n");

    /* Go through the entire account hash to find dbusers */
    /* Seperate hash for dbusers? */
    for (i = 0; i < accounts->size; i++) {
        bp = accounts->buckets[i];
        
        /* There is an account in here */
        if (bp) {
            for (;bp; bp = bp->next) {
                ap = (account *)bp->pointer;
                if (ap->dbuser) {
                    /* Save this user */
                    fprintf(fp, "[%s]\n", ap->name);
                    fprintf(fp, "flags=%d\n", ap->dbuser->flags);
                    fprintf(fp, "lastseen=%lu\n", ap->dbuser->lastseen);
                    fprintf(fp, "trigger=%d\n", ap->dbuser->trigger);
                    /* Now for all the chanlevels */
                    for (clp = ap->dbuser->chanlevels; clp; clp = clp->nextbyaccount) {
                        fprintf(fp, "<%s>\n", clp->channel->name);
                        fprintf(fp, "lastchanged=%lu\n", clp->lastchanged);
                        fprintf(fp, "lastseen=%lu\n", clp->lastseen);
                        fprintf(fp, "flags=%d\n", clp->flags);
                    }
                    fprintf(fp, "\n");
                    saved++;
                }
            }
        }
    }

    fclose(fp);

    return saved;
}

void savedatabases(void *p) {
    int userdb, chandb;

    chandb = savechandb(getconf("chanfile", "ircbot.chanfile"));
    userdb = saveuserdb(getconf("userfile", "ircbot.userfile"));

    printlog("-- Saved %d channels and %d users", chandb, userdb);
}
